#define VKW_DEVICE_FUNCTION_LIST \
    X(vkDestroyDevice) \
    X(vkDeviceWaitIdle) \
    X(vkGetDeviceQueue) \
    X(vkCreateCommandPool) \
    X(vkResetCommandPool) \
    X(vkDestroyCommandPool) \
    X(vkAllocateCommandBuffers) \
    X(vkResetCommandBuffer) \
    X(vkFreeCommandBuffers) \
    X(vkBeginCommandBuffer) \
    X(vkEndCommandBuffer) \
    X(vkQueueSubmit) \
    X(vkCmdExecuteCommands) \
    X(vkCreateFence) \
    X(vkDestroyFence) \
    X(vkGetFenceStatus) \
    X(vkResetFences) \
    X(vkWaitForFences) \
    X(vkCreateSemaphore) \
    X(vkDestroySemaphore) \
    X(vkCreateEvent) \
    X(vkDestroyEvent) \
    X(vkGetEventStatus) \
    X(vkSetEvent) \
    X(vkResetEvent) \
    X(vkCmdSetEvent) \
    X(vkCmdResetEvent) \
    X(vkCmdWaitEvents) \
    X(vkCmdPipelineBarrier) \
    X(vkCreateRenderPass) \
    X(vkDestroyRenderPass) \
    X(vkCreateFramebuffer) \
    X(vkDestroyFramebuffer) \
    X(vkCmdBeginRenderPass) \
    X(vkGetRenderAreaGranularity) \
    X(vkCmdNextSubpass) \
    X(vkCmdEndRenderPass) \
    X(vkCreateShaderModule) \
    X(vkDestroyShaderModule) \
    X(vkCreateComputePipelines) \
    X(vkCreateGraphicsPipelines) \
    X(vkDestroyPipeline) \
    X(vkCreatePipelineCache) \
    X(vkMergePipelineCaches) \
    X(vkGetPipelineCacheData) \
    X(vkDestroyPipelineCache) \
    X(vkCmdBindPipeline) \
    X(vkGetPhysicalDeviceMemoryProperties) \
    X(vkAllocateMemory) \
    X(vkFreeMemory) \
    X(vkMapMemory) \
    X(vkFlushMappedMemoryRanges) \
    X(vkInvalidateMappedMemoryRanges) \
    X(vkUnmapMemory) \
    X(vkGetDeviceMemoryCommitment) \
    X(vkCreateBuffer) \
    X(vkDestroyBuffer) \
    X(vkCreateBufferView) \
    X(vkDestroyBufferView) \
    X(vkCreateImage) \
    X(vkGetImageSubresourceLayout) \
    X(vkDestroyImage) \
    X(vkCreateImageView) \
    X(vkDestroyImageView) \
    X(vkGetBufferMemoryRequirements) \
    X(vkGetImageMemoryRequirements) \
    X(vkBindBufferMemory) \
    X(vkBindImageMemory) \
    X(vkCreateSampler) \
    X(vkDestroySampler) \
    X(vkCreateDescriptorSetLayout) \
    X(vkDestroyDescriptorSetLayout) \
    X(vkCreatePipelineLayout) \
    X(vkDestroyPipelineLayout) \
    X(vkCreateDescriptorPool) \
    X(vkDestroyDescriptorPool) \
    X(vkAllocateDescriptorSets) \
    X(vkFreeDescriptorSets) \
    X(vkResetDescriptorPool) \
    X(vkUpdateDescriptorSets) \
    X(vkCmdBindDescriptorSets) \
    X(vkCmdPushConstants) \
    X(vkCmdClearColorImage) \
    X(vkCmdClearDepthStencilImage) \
    X(vkCmdClearAttachments) \
    X(vkCmdFillBuffer) \
    X(vkCmdUpdateBuffer) \
    X(vkCreateQueryPool) \
    X(vkDestroyQueryPool) \
    X(vkCmdResetQueryPool) \
    X(vkCmdBeginQuery) \
    X(vkCmdEndQuery) \
    X(vkGetQueryPoolResults) \
    X(vkCmdCopyQueryPoolResults) \
    X(vkCmdWriteTimestamp) \
    X(vkCmdCopyBuffer) \
    X(vkCmdCopyImage) \
    X(vkCmdCopyBufferToImage) \
    X(vkCmdCopyImageToBuffer) \
    X(vkCmdBlitImage) \
    X(vkCmdResolveImage) \
    X(vkCmdBindIndexBuffer) \
    X(vkCmdDraw) \
    X(vkCmdDrawIndexed) \
    X(vkCmdDrawIndirect) \
    X(vkCmdDrawIndexedIndirect) \
    X(vkCmdBindVertexBuffers) \
    X(vkCmdSetViewport) \
    X(vkCmdSetLineWidth) \
    X(vkCmdSetDepthBias) \
    X(vkCmdSetBlendConstants) \
    X(vkCmdSetScissor) \
    X(vkCmdSetDepthBounds) \
    X(vkCmdSetStencilCompareMask) \
    X(vkCmdSetStencilWriteMask) \
    X(vkCmdSetStencilReference) \
    X(vkGetPhysicalDeviceSparseImageFormatProperties) \
    X(vkGetImageSparseMemoryRequirements) \
    X(vkQueueBindSparse) \
    X(vkCmdDispatch) \
    X(vkCmdDispatchIndirect)
